# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V3m9LgKqTcobu1suHNF-_nUBk_WgsAoV

# Nueva sección corte 1
"""

print("hola mundo")



nombre = input("cual es tu nombre ")
print("hola mundo de ", nombre)

NOMBRE= "D4V1D"
EDAD = 27
ALTURA = 1.70
CORREO = "JDPINZON@123"
SOLTERO = False

print ("tipos de datos")
print(type(NOMBRE))
print(type(SOLTERO))
print(type(ALTURA))
print(type(CORREO))
print(type(EDAD))

print("HOLA", NOMBRE, "TIENES", EDAD-10)

import math
vab1=12
vab2=22

suma = vab1 + vab2
resta = vab1 - vab2
multiplicacion = vab1 * vab2
division = vab1 / vab2
raiz = math.sqrt(vab1 + vab2)


print(f" suma entre {vab1} y {vab2} es {suma}")
print(f" resta entre {vab1} y {vab2} es {resta}")
print(f" multiplicacion entre {vab1} y {vab2} es {multiplicacion}")
print(f" division entre {vab1} y {vab2} es {division}")
print(f" la raiz es {raiz}")



nombre = input("cual es tu nombre ")
print("por favor indicame 3 notas para calcular el promedio")

nota1 = float(input("nota 1: "))
nota2 =float(input("nota 2: "))
nota3 =float(input("nota 3: "))

suma= (nota1+nota2+nota3)
promedio = suma/3
print("suma de notas", suma)
print("el promedio de notas es",promedio)

print("bienvenido a la tienda pulgas")
nombredelproducto="tomate"
cantidad=int(input("¿cuantos tomates compraste?"))
preciotomate=1000
subtotalpreciotomate * cantidad
print("el subtotales",subtotal)


vabIVA = 19/100
costoIVA = vabIVA * subtotal
print(costo de IVA19%)

RETO 1

Una tienda de tecnología necesita calcular
 el valor de una compra realizada por un
 cliente. Para ello, se requiere desarrollar
 un programa en Python que permita registrar
 la cantidad de productos comprados y el precio
 unitario de cada producto.

El programa debe calcular y mostrar:

El subtotal de la compra. - Santiago Peña Rua
El valor del IVA (19%). - Nicolas Villamizar
El total a pagar.
El valor correspondiente a un descuento del 10%
 sobre el subtotal.
El total final después de aplicar el descuento y
 sumar el IVA

cantidad = int(input("Ingrese la cantidad de productos: "))

subtotal = 0

for i in range(cantidad):
    precio = float(input("Ingrese el precio del producto: "))
    subtotal = subtotal + precio

iva = subtotal * 0.19

total = subtotal + iva

descuento = subtotal * 0.10

total_final = subtotal - descuento + iva

print("Subtotal:", subtotal)
print("IVA (19%):", iva)
print("Total a pagar:", total)
print("Descuento (10%):", descuento)
print("Total final:", total_final)

"""Ejercicio 1 — Cafetería universitaria (2,5 puntos)

Una cafetería universitaria desea automatizar el cálculo de una compra. El programa debe solicitar al usuario la cantidad de productos comprados y el precio unitario de cada producto.

El programa debe:

a. (0,5 puntos): Calcular y mostrar el subtotal de la compra.

b. (0,5 puntos): Calcular y mostrar el 10% de descuento aplicado sobre el subtotal.

c. (0,5 puntos): Calcular y mostrar el IVA del 19% sobre el subtotal.

d. (0,5 puntos): Calcular y mostrar el total a pagar después del descuento y antes del IVA.

e. (0,5 puntos): Calcular y mostrar el valor final a pagar, incluyendo el IVA.

EJERCICIO 1
"""

cantidad = int(input("Ingrese la cantidad de productos: "))
precio = float(input("Ingrese el precio de cada producto: "))

subtotal = cantidad * precio

descuento = subtotal * 0.10

iva = subtotal * 0.19

total_antes_iva = subtotal - descuento

total_final = total_antes_iva + iva

print("Subtotal:", subtotal)
print("Descuento del 10%:", descuento)
print("IVA del 19%:", iva)
print("Total a pagar antes del IVA:", total_antes_iva)
print("Valor final a pagar:", total_final)

"""EJERCICIO 2

Ejercicio 2 — Viaje en automóvil (2,5 puntos)

Una persona desea calcular cuánto dinero gastará en combustible durante un viaje. Para ello, conoce la distancia del viaje en kilómetros, el rendimiento del automóvil en kilómetros por litro y el precio de un litro de gasolina.

El programa debe:

a. (0,5 puntos): Calcular y mostrar la cantidad de litros de gasolina necesarios para realizar el viaje.

b. (0,5 puntos): Calcular y mostrar el costo total del combustible.

c. (0,5 puntos): Calcular y mostrar el costo del combustible si el precio aumenta un 8%.

d. (0,5 puntos): Calcular y mostrar cuánto corresponde pagar si el costo total se divide entre 3 personas.

e. (0,5 puntos): Calcular y mostrar el costo total del viaje ida y vuelta.


Calificación total: 5,0 puntos

Ejercicio 1: 2,5 puntos

Ejercicio 2: 2,5 puntos
"""



distancia = 100 #kms
rendimiento_ferrari = 7 #km/litro
precio_gasolina = 5019 #precio extra/litro

litros_necesarios = distancia / rendimiento_ferrari
print("cantidad litros necesarios para este viaje es de ",litros_necesarios)

costo_gasolina = precio_gasolina * litros_necesarios
print("el costo de la gasolina para este viaje es de",costo_gasolina)

aumento_combustible  = precio_gasolina * 1.08
print("el coto del conbustible cuando sube 8% es de", aumento_combustible)

costo_entre_3 = costo_gasolina / 3
print("pagando entre 3 sale a",costo_entre_3)

ida_y_vuelta = costo_gasolina * 2
print("costo total ida y vuelta",ida_vuelta)

num1 = int(input("Dame un numero: "))
num2 = int(input("Dame un numero: "))
num3 = int(input("Dame un numero: "))

suma=num1+num2+num3

print("La suma es: ", suma)

cuantosNumerosSumar = int(input("¿Cuantos numeros deseas sumar? "))

acumuladoSuma=0

for i in range(cuantosNumerosSumar):
  numero = int(input("Dame el numero que quieres sumar"))
  acumuladoSuma = acumuladoSuma + numero

print("La suma es ", acumuladoSuma)

for i in range(5):
  print("i=",i)



for i in range(5):
  print("Esta por dentro del bucle: ", i, "vez")
print("Está por fuera")



#Caso 1
print("#Caso 1")
for i in range(5):
  print("i=", i)

#Caso 2
print("#Caso 2")
for i in range(1,5):
  print("i=", i)

#Caso 3
print("#Caso 3")
for i in range(1,5,2):
  print("i=", i)

notas = [3.5, 4.2, 2.8, 5.0]

for nota in notas:
    print("La nota es:", nota)

notas = [3.5, 4.2, 3, 5.0]
suma = 0
for nota in notas:
    suma = suma + nota
print("Promedio:", suma / len(notas))

edad = int(input("Tu edad: "))

while edad < 1 or edad >50:
    print("Eso no es válido")
    edad = int(input("Tu edad: "))
print("Bienvenido")

"""Tipo de dato: entero (int)
Enunciado: Solicita al usuario su edad y clasifícalo en una de las siguientes categorías: niño (0 a 12 años), adolescente (13 a 17 años), adulto (18 a 59 años) o adulto mayor (60 años o más). Si el usuario ingresa un número negativo, muestra un mensaje de error indicando que la edad no es válida.


•	1. ¿Qué ocurre si el usuario ingresa un texto (por ejemplo, "quince") en lugar de un número? sale un error ¿Por qué crees que sucede eso? por que no esta especificado la escritura de la edad en letras
•	2. ¿Por qué es necesario usar int() al capturar la edad y qué pasaría si no lo hicieras? por que si no se hace la programacion tendria problema para capturar la informacion en numeros
•	3. ¿Cómo decidiste el orden de tus condiciones (if, elif, else) y por qué ese orden es importante?
Respuesta: por que if es la primera posibilidad eliff otras posibilidades y else lo que queda si ninguna se cumple
y es importante el orden ya que el programa leee de arriba hacia abajo

"""

edad = int(input("Ingrese su edad: "))

if edad < 0:
    print("Edad no válida")
elif edad <= 12:
    print("Niño")
elif edad <=17:
    print ("adolecente")
elif edad<=59:
    print("adulto")
else:
    print ("adulto mayor")
# completa el resto de condiciones...

"""Pide al usuario su nota final del curso (escala 0.0 a 5.0). El programa debe indicar si el estudiante "Aprobó" (nota mayor o igual a 3.0), está en "Habilitación" (nota entre 2.5 y 2.99) o "Reprobó" (nota menor a 2.5). Además, si la nota ingresada es mayor a 5.0 o menor a 0.0, el programa debe informar que el valor está fuera de rango.

riesgo propio de los números decimales.
•	2. ¿Por qué se debe validar primero el rango fuera de límites (menor a 0.0 o mayor a 5.0) antes que las demás condiciones?
•	3. Si cambiaras el límite de habilitación a 2.6, ¿qué línea de tu código modificarías y qué impacto tendría en los resultados?
"""

nota = float(input("Ingrese su nota final (0.0 a 5.0): "))

if nota < 0.0 or nota > 5.0:
    print("Valor fuera de rango")
elif nota >= 3.5:
    print("Aprobó")
elif nota >= 2.3:
    print("Habilitacion")
else:
    print("Reprobo")

"""Tipo de dato: cadena de texto (str)
Enunciado: Solicita al usuario que ingrese su rol dentro de un sistema académico, escribiendo una de estas opciones: "estudiante", "docente" o "administrador". El programa debe mostrar un mensaje distinto de bienvenida según el rol ingresado, y si el texto no coincide con ninguna opción válida (sin importar mayúsculas o minúsculas), debe indicar "Rol no reconocido".
•	1. Este ejercicio usa dos valores de entrada para tomar una sola decisión. ¿Qué otras situaciones de la vida real conoces donde se necesiten varias variables antes de decidir algo?
•	2. ¿Qué pasaría en tu programa si el usuario ingresa una estatura de 0? Explica por qué ocurre y cómo lo evitarías.
•	3. ¿Consideras que esta clasificación por rangos numéricos es siempre justa o suficiente para evaluar la salud de una persona? Justifica tu respuesta.
Respuesta:

"""

rol=input("ingrese su rol(estudiante/docente/administrador):")
print(rol)

rol=rol.lower().strip()
print(rol)


if rol==("estudiante"):
   print("Bienvenido/a estudiante")
elif rol==("docente"):
   print("Bienvenido/a docente")
elif rol==("admnistrador"):
   print("Bienvenido/a administrador")
else:
   print("Rol no reconocido")

"""Tipo de dato: texto convertido a valor lógico (bool) + float
Enunciado: Un almacén ofrece 15% de descuento a estudiantes y 5% adicional si la compra supera $200.000. Pide al usuario el valor de su compra (float) y si es estudiante, respondiendo "si" o "no" (texto). Convierte esa respuesta a un valor booleano (por ejemplo, es_estudiante = respuesta.lower() == "si") y usa condicionales para calcular y mostrar el valor final a pagar.

"""

compra = float(input("Ingrese el valor de la compra: "))
respuesta = input("¿Es estudiante? (si/no): ")
es_estudiante = respuesta == "si"

descuento = 0.0
if es_estudiante:
    descuento += 0.15

"""estructuras de datos"""

listadenumeros = [2,3,4,100]
numero= 5
listanumeros
print(type(listanumeros))
print(len("tamaño lista ->",len(listanumeros))


print(listanumeros)
print("los valores en la lista son:")
i=0
for valor in listanumeros:
  print(valor)
  i+=1